// Code generated by goctl. DO NOT EDIT!
// Source: limit.proto

package server

import (
	"context"

	"go_zero_limit/rpc/limit/internal/logic"
	"go_zero_limit/rpc/limit/internal/svc"
	"go_zero_limit/rpc/limit/limit"
)

type LimitServer struct {
	svcCtx *svc.ServiceContext
	limit.UnimplementedLimitServer
}

func NewLimitServer(svcCtx *svc.ServiceContext) *LimitServer {
	return &LimitServer{
		svcCtx: svcCtx,
	}
}

func (s *LimitServer) IsLimit(ctx context.Context, in *limit.LimitReq) (*limit.LimitResp, error) {
	l := logic.NewIsLimitLogic(ctx, s.svcCtx)
	return l.IsLimit(in)
}
