// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: limit.proto

package limit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LimitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LimitReq) Reset() {
	*x = LimitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_limit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitReq) ProtoMessage() {}

func (x *LimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_limit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitReq.ProtoReflect.Descriptor instead.
func (*LimitReq) Descriptor() ([]byte, []int) {
	return file_limit_proto_rawDescGZIP(), []int{0}
}

func (x *LimitReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LimitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLimit bool `protobuf:"varint,1,opt,name=isLimit,proto3" json:"isLimit,omitempty"`
}

func (x *LimitResp) Reset() {
	*x = LimitResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_limit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LimitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitResp) ProtoMessage() {}

func (x *LimitResp) ProtoReflect() protoreflect.Message {
	mi := &file_limit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitResp.ProtoReflect.Descriptor instead.
func (*LimitResp) Descriptor() ([]byte, []int) {
	return file_limit_proto_rawDescGZIP(), []int{1}
}

func (x *LimitResp) GetIsLimit() bool {
	if x != nil {
		return x.IsLimit
	}
	return false
}

var File_limit_proto protoreflect.FileDescriptor

var file_limit_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x1c, 0x0a, 0x08, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x25, 0x0a, 0x09, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x32, 0x35, 0x0a, 0x05, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x49, 0x73, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x0f, 0x2e,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_limit_proto_rawDescOnce sync.Once
	file_limit_proto_rawDescData = file_limit_proto_rawDesc
)

func file_limit_proto_rawDescGZIP() []byte {
	file_limit_proto_rawDescOnce.Do(func() {
		file_limit_proto_rawDescData = protoimpl.X.CompressGZIP(file_limit_proto_rawDescData)
	})
	return file_limit_proto_rawDescData
}

var file_limit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_limit_proto_goTypes = []interface{}{
	(*LimitReq)(nil),  // 0: limit.LimitReq
	(*LimitResp)(nil), // 1: limit.LimitResp
}
var file_limit_proto_depIdxs = []int32{
	0, // 0: limit.Limit.IsLimit:input_type -> limit.LimitReq
	1, // 1: limit.Limit.IsLimit:output_type -> limit.LimitResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_limit_proto_init() }
func file_limit_proto_init() {
	if File_limit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_limit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_limit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LimitResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_limit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limit_proto_goTypes,
		DependencyIndexes: file_limit_proto_depIdxs,
		MessageInfos:      file_limit_proto_msgTypes,
	}.Build()
	File_limit_proto = out.File
	file_limit_proto_rawDesc = nil
	file_limit_proto_goTypes = nil
	file_limit_proto_depIdxs = nil
}
